### ISSUE TITLE
Unable to authenticate: unsupported OAuth method

### ISSUE THREAD

**Issue by diije** [antoineeripret/gsc_wrapper#2] opened 2024-01-22 14:52 UTC
Hello,

When trying to first authenticate, I copy/paste the URL in my browser then get this error message:

<img width="466" alt="Capture d’écran 2024-01-22 à 15 46 59" src="https://github.com/antoineeripret/gsc_wrapper/assets/1700264/0aa83033-8716-4cb5-a5e7-0a734f2926ec">

The error details:

<img width="310" alt="Capture d’écran 2024-01-22 à 15 48 03" src="https://github.com/antoineeripret/gsc_wrapper/assets/1700264/f16b3602-2239-4f51-8713-a326e65b81c4">

And the related links:  
- https://support.google.com/accounts/answer/12379384  
- https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

My code (pretty similar to the readme):  

```
account = gscwrapper.generate_auth(
        'auth/secret.json',
        serialize='auth/token.json',
    )
```

It seems the authentication method isn't supported anymore by Google's APIs.  
I was able to bypass this by using tokens from another project, but this is definitely a blocker 😬

**Comment by antoineeripret** [comment] 2024-01-22 16:00
Hi @diije : 

- did you follow the steps explained in the [Quickstart](https://github.com/antoineeripret/gsc_wrapper?tab=readme-ov-file#quickstart) section? If you don't do exactly what is explained, the OAuth flow will indeed break. 
- Did you add your email as a test user for your application? 

Thanks !

**Comment by diije** [comment] 2024-01-23 14:47
Yep my email is indeed in the test users list (greyed out obviously):
<img width="540" alt="Capture d’écran 2024-01-23 à 15 45 17" src="https://github.com/antoineeripret/gsc_wrapper/assets/1700264/c806c8fe-0c12-492a-a869-be84aba55d31">

FWIW (my turn) the credentials I used to bypass the auth process come from an app that's in production mode.

**Comment by antoineeripret** [comment] 2024-01-23 15:27
@diije, 

- I've followed my own instructions from the **quickstart** section (new project, new app etc...) 
- I've created a venv in my computer, ran the pip install and ran the following code: 

```python
import gscwrapper
#authentificate 
account = gscwrapper.generate_auth(
    '/Users/antoine/Librerías Python/debug-julien/client_secret_julien.json', 
    serialize='/Users/antoine/Librerías Python/debug-julien/credentials.json'
)

print(account.list_webproperties())
```

- I got the link from the terminal 
- Opened it and managed to go through and get the oauth code 
- Got the result from the GSC API 

You must have skipped a step, because I'm honestly not able to reproduce your issue. Did you follow all the instructions from the **quickstart**?

**Comment by antoineeripret** [comment] 2024-02-05 08:46
Hey @diije : closing this issue. 

- I've checked with other users on Friday, and they don't have the issue you described 
- I've added an alternative auth method using a service account file, that you can use if, for whatever reason, this one doesn't work 

Do not hesitate to open the issue again if you don't manage to auth.

**Closed by antoineeripret** 2024-02-05 08:46 UTC
